# K8s manifest to patch jhub deployment to point to an existing share

spec:
  template:
    spec:
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: jhub-vre-singleuser-preprovisioned-manila-pvc
