apiVersion: v1
kind: ConfigMap
metadata:
  name: jhub-profiles
  namespace: jhub
data:
  values.yaml: |
    singleuser:
      profileList:
        - display_name: "Default environment"
          description: "Based on a scipy notebook environment with a python-3.11 kernel, the rucio jupyterlab extension and the reana client installed."
          default: true
        