---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rucio-root-account
  namespace: rucio
spec:
  encryptedData:
    root-password: AgCUzPrQdP85cEoyChFZWPDyYhtT8ZC5duBr3l6q+0nHVCJGOH+gmUhpxPHe4Obv3LJrIY08MfBc1d+hRCHE1sss66ORIFsoWTA+M5r/S6y8am8dslN4lSQykd6AWAEtf2Lor79IyEmBW4b7R4xrwkt2nmJ93H6y62vqJjqHi5hJs3PaqdKXY0WkHMPMCrLgmhuCB06n5VrUSSE4MhrSRiGPaU9/IxGP+ybmolWPp6vlMYmDtNeSvAPvwxX5XNUs1bsy3H8QncmBxT6ZbM498/8HUAGd+0TwgiBGaqjdMSbS9L6tuPhAjaF68uchp0u1TMtlUTSq/F7k10R2rVLV13I+9M66j31vQ8f8Q84T66kBJoRbDZ6pb5GSA1v0gX0xpNQ2c9MUa445nZ5KyYjqpmkpUGmqyOHRSRYdhl7nlmo8TGXO/Ed4ASQnmxChmD9Ej+KEI3H6QwobeR9GSILH8ozvzeAjWqo6kpiM+GmZiVnh8ueCoQKZ8LNLzuDHd4B+NQV5+epE5QFG89yefpi+cLu4aYd/+QW+eCl3dBreCRgcP7xjCmvZDZPelsxTRsWBntGZuOza+eN2MvKR43QIjoA/W7/L/2zApg5o5Yy28rLU05SFLfc/8jRoFOwZRje57M7SjZCPZhFF7kgda9mmMaIRbHx9leyZM0heaipD0giEch1LUzv8pX21P7e1PJtYEn00yQqunpr45TVXneM9nRzjKb5KpzqBqbmGmA==
    root-username: AgBqP1fgeoJx3cIT2adPUy4Xittg1u/DrlfaSNwN4YoyzeZW/joQQayX2zOZfO3EmgkoAIz0gZxNCuuTkX/99Am6lJnCUmEG6yIO0xUA4py7xck7MM1RGv9J+MVQLL2shgwRKsEkkTMILTrGseYJgxSblFb/WImYjjrt/sJpNNBY6tHQCX9zN9OyIaS4vL1JS0BkfhvF2WBJlMS0BMsj1iOSjFHajJemez6ZVLsr1r3ysWwfJoGvMxaipG+bO3X9KFltOO/8D67rAJdM+gGuaCkvThIFJQJWONr8Ydxf7/5F8yVN7loDzDVm/wHliPih8ty/IO6DUs/Fz7BwhPYgv3aNf9w8VKPLP2Fb3nCS+CMS5KZd0lbs2+J31uZKieN5XsqjNkymsQiPuvlKSg40qPyOhglxMY6bsvOjQGRqntIIMvBcgGDeeI+CaXkaH0ZhwEAz58UmWvCJvssAHFRSDASfudISnR39k6urjYD/MznLl138608lEh09n4QdNJo2rc9/VzWk9hGq6/JJp3vXBEOnoauqPkzIIZdOVquEkB8nvJUzdhH+cdS3plLc7Q4NkxwvDWfwdr/u3BbicbbvXqnIjAAPfu+d/18DNhQkvdZeWUlYLoWxvxFw8mM4K6sJF02yJ/lBEl0DCjE3xGp6GECDRX/yiEmGH83FzLa/XfJQL21EPVmHARchbkjLUOrvEc3vyNwNMPw=
  template:
    metadata:
      creationTimestamp: null
      name: rucio-root-account
      namespace: rucio
